name: CI

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fail if previous workflow failed
        run: exit 1
        if: ${{ github.event.workflow_run.conclusion != 'success' }}

      - uses: actions/checkout@v4
      - name: Hello world
        run: echo "Build passed! 🎉"